#ifndef MYCHARTMEATURELIB_LIB_GLOBAL_H
#define MYCHARTMEATURELIB_LIB_GLOBAL_H

#include <QtCore/qglobal.h>
#include <qstring.h>

#ifdef MYCHARTMEATURELIB_LIB
# define MYCHARTMEATURELIB_EXPORT Q_DECL_EXPORT
#else
# define MYCHARTMEATURELIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MYCHARTMEATURELIB_LIB_GLOBAL_H
