//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维管线 系统架构设计
//  @ File Name : igeopoint.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/ivec.h"

namespace Core
{
	IVec3::IVec3(const IVec3& value)
    {
		this->X = value.X;
		this->Y = value.Y;
		this->Z = value.Z;
    }

	IVec3::IVec3(const double& x, const double y, const double& z)
		: X(x), Y(y), Z(z)
	{
	
	}
    
	IVec3::~IVec3()
    {
    
    }

	IVec4::IVec4(const IVec4& value)
    {
		this->X = value.X;
		this->Y = value.Y;
		this->Z = value.Z;
		this->W = value.W;
    }

	IVec4::IVec4(const double& x , const double y, const double& z, const double& w)
		: X(x), Y(y), Z(z), W(w)
	{

	}

	IVec4::~IVec4()
    {
    
    }
    
}
