//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeoline.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGEOLINE_H)
#define _IGEOLINE_H

#include "framework/common/isceneobject.h"



namespace Core
{
	/// <summary>
	/// IGeoLine类：几何线组织与渲染对象，
	/// 用来表达空间地理线串,由一系列点坐标构成。
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGeoLine : public Common::ISceneObject
    {
    public:

		/// <summary>
		/// 构造函数
		/// </summary>
		IGeoLine();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		IGeoLine(osgEarth::MapNode* pRefMapNode);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IGeoLine();

		/// <summary>
		/// 获取几何图形
		/// </summary>
		virtual std::vector<osg::Vec3d>& getGeometry();

	protected:
		std::vector<osg::Vec3d> m_vecPoint;

    };
}

#endif  //_IGEOLINE_H
