//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeorect.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGEORECT_H)
#define _IGEORECT_H

#include "framework/common/isceneobject.h"

// 地理矩形
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGeoRect : public Common::ISceneObject
    {
    public:
        void getPostion();
        void setPosition();
        void getWidth();
        void setWidth();
        void getHeight();
        void setHeight();
    };
}

#endif  //_IGEORECT_H
