//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeopoint.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGEOPOINT_H)
#define _IGEOPOINT_H

#include "framework/common/isceneobject.h"


// 地理坐标点
namespace Core
{
	/// <summary>
	/// IGeoPoint类：地理几何点类，用于提供表达与渲染空间点的接口
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGeoPoint : public Common::ISceneObject
	{
    public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IGeoPoint();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		IGeoPoint(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IGeoPoint();

    };
}

#endif  //_IGEOPOINT_H
