//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeopolygon.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGEOPOLYGON_H)
#define _IGEOPOLYGON_H

#include "framework/common/isceneobject.h"



namespace Core
{
	/// <summary>
	/// IGeoPolygon类：地理多边形类，通过一个点列来组织与渲染多边形
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGeoPolygon : public Common::ISceneObject
    {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IGeoPolygon();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		IGeoPolygon(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IGeoPolygon();

		virtual bool contain(const osg::Vec3d& geoPoint);
    };
}

#endif  //_IGEOPOLYGON_H
