//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeomodel.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGEOMODEL_H)
#define _IGEOMODEL_H

#include "framework/common/isceneobject.h"

namespace Core
{
	class ISpatialParameter;
	/// <summary>
	/// IGeoModel:模型接口类,用于渲染本地各种三维模型，比如：.osg,osgb,3ds,ive等
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGeoModel : public Common::ISceneObject
    {
    public:

		/// <summary>
		/// 构造函数
		/// </summary>
		IGeoModel();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		IGeoModel(osgEarth::MapNode* pRefMapNode);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IGeoModel();

		/// <summary>
		/// 获取空间参考
		/// </summary>
		virtual Core::ISpatialParameter* getOrCreateSpatialParameter();

	protected:
		Core::ISpatialParameter* mpSpatialParameter;
    };
}

#endif  //_IGEOMODEL_H
