//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igrouplayer.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IGROUPLAYER_H)
#define _IGROUPLAYER_H

#include "framework/core//ilayer.h"
#include "iobjectcontainer.h"

// 图层组类，提供对管线系统图层数据的管理与编辑功能
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IGroupLayer : public Core::ILayer, public IObjectContainer
    {
    public:
		IGroupLayer();

		IGroupLayer(osgEarth::MapNode* pRefMapNode);

		virtual ~IGroupLayer();
    };
}

#endif  //_IGROUPLAYER_H
