//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ilayermanager.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ILAYERMANAGER_H)
#define _ILAYERMANAGER_H

#include "framework/core/iobjectcontainer.h"


// 图层管理类，提供对管线系统图层组数据的管理与编辑功能
//单例对象，管理管线系统所有的图层数据
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ILayerManager : public Core::IObjectContainer
    {
    public:
		
		virtual ~ILayerManager();

		static ILayerManager* instance();

		static void releaseInstance();

	private:

		ILayerManager();

		
    };
}

#endif  //_ILAYERMANAGER_H
