//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ilayer.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ILAYER_H)
#define _ILAYER_H

#include "framework/common/isceneobject.h"
#include "iobjectcontainer.h"


namespace Core
{
	/// <summary>
	/// ILayer类:场景图层基类，以图层的形式提供对三维平台系统对象数据的管理与渲染功能
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ILayer : public Common::ISceneObject, public IObjectContainer
    {
    public:
		/// <summary>
		/// 构造函数
		/// </summary>
		ILayer();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		ILayer(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~ILayer();
		/// <summary>
		/// 设置图层显隐
		/// </summary>
		virtual void setVisible(const bool& visible);
    };
}

#endif  //_ILAYER_H
