//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : irasterlayer.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IRASTERLAYER_H)
#define _IRASTERLAYER_H

#include "ilayer.h"
#include <osgEarth/Map>

// 栅格图层类，提供对栅格数据的存储与管理功能
//主要提供对WMTS切片数据的加载与渲染
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IRasterLayer : public ILayer
    {
    public:
		IRasterLayer();

		IRasterLayer(osgEarth::Map* pRefMap);

		virtual ~IRasterLayer();

		virtual void setTransparet(const double& transparent);

		virtual double getTransparet();

	protected:
		double mTransparent;
		osgEarth::Map* mpRefMap;
    };
}

#endif  //_IRASTERLAYER_H
