//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ispatialparameter.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ISPATIALPARAMETER_H)
#define _ISPATIALPARAMETER_H

#include <osg/Vec3d>
#include "framework/vr_globeframework_global.h"

// 地理空间参数
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ISpatialParameter
    {
    public:

		ISpatialParameter();

		virtual ~ISpatialParameter();

        osg::Vec3d& getRotate();

		void setRotate(const  osg::Vec3d& rotate);

		osg::Vec3d& getScale();

		void setScale(const  osg::Vec3d& scale);

		osg::Vec3d& getOffset();

		void setOffset(const  osg::Vec3d& offset);

	private:
		osg::Vec3d mRotate;
		osg::Vec3d mScale;
		osg::Vec3d mOffset;
    };
}

#endif  //_ISPATIALPARAMETER_H
