//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itopologygraphy.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ITOPOLOGYGRAPHY_H)
#define _ITOPOLOGYGRAPHY_H

#include "igrouplayer.h"


// 拓扑关系图
namespace Core
{
	class ITopologyArc;
	class ITopologyPoint;
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ITopologyGraphy : public Core::ILayer
    {
    public:
		ITopologyGraphy();

		ITopologyGraphy(osgEarth::MapNode* pRefMapNode);

		virtual ~ITopologyGraphy();

        Core::IObjectContainer* getArcsByStartPoint(const std::string& id);

		Core::IObjectContainer* getArcsByEndPoint(const std::string& id);

		Core::IObjectContainer* getArcs(const std::string& id);

		Core::ITopologyPoint* getTopologyPoint(const double& lon,const double& lat,const double& alt);

		Core::ITopologyArc* getTopologyArc(const std::string& id1, const std::string& id2);

		virtual bool loadToScene();

		virtual bool renderToScene();

	protected:
		IObjectContainer mTopologyPoints;
    };
}

#endif  //_ITOPOLOGYGRAPHY_H
