//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维管线 系统架构设计
//  @ File Name : itopologycreator.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ITOPOLOGYCREATOR_H)
#define _ITOPOLOGYCREATOR_H

//#include "pipemodel/vr_globepipemodel_global.h"

// 拓扑关系构建算法类
namespace Core
{
	class VR_GLOBEFPIPYMODEL_EXPORT ITopologyCreator
    {
    public:
        void createTopologyAccordingLineLayer();
    };
}

#endif  //_ITOPOLOGYCREATOR_H
