//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itopologypoint.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ITOPOLOGYPOINT_H)
#define _ITOPOLOGYPOINT_H

#include "framework/common/iobject.h"
#include "igeopoint.h"

// 拓扑节点
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ITopologyPoint : public IGeoPoint
    {
    public:
        void perform();
    };
}

#endif  //_ITOPOLOGYPOINT_H
