//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itopologyarc.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ITOPOLOGYARC_H)
#define _ITOPOLOGYARC_H

#include "framework/common/iobject.h"
#include "igeosegment.h"
#include "itopologypoint.h"

// 拓扑弧段
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ITopologyArc : public Common::IObject/*, public IGeoSegment*/
    {
    public:

		ITopologyArc();

		virtual ~ITopologyArc();

		virtual Core::ITopologyPoint* getStartPoint();

		virtual void setStartPoint(Core::ITopologyPoint* pStartTopologyPoint);

		virtual Core::ITopologyPoint* getEndPoint();

		virtual void setEndPoint(Core::ITopologyPoint* pEndTopologyPoint);

	protected:
		Core::ITopologyPoint* mpRefStartTopologyPoint;
		Core::ITopologyPoint* mpRefEndTopologyPoint;

    };
}

#endif  //_ITOPOLOGYARC_H
