//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ivectorlayer.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IVECTORLAYER_H)
#define _IVECTORLAYER_H

#include "ilayer.h"

// 矢量图层类，提供对场景矢量模型数据的存储与管理功能
namespace Core
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT IVectorLayer : public ILayer
    {
    public:
        void perform();
    };
}

#endif  //_IVECTORLAYER_H
