//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeoarc.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOARC_H)
#define _CGEOARC_H

#include "framework/core/igeopoint.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class VR_GEOGRAPHIC_EXPORT CGeoArc : 
		public Core::IGeoPoint
	{
	public:
		void Operation1();
	};

}

#endif  //_CGEOARC_H
