//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeobezierline.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOBEZIERLINE_H)
#define _CGEOBEZIERLINE_H

#include "framework/core/igeoline.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class VR_GEOGRAPHIC_EXPORT CGeoBezierLine 
		: public Core::IGeoLine
	{
	public:
		void Operation1();
	};
}

#endif  //_CGEOBEZIERLINE_H
