//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeocoattailleanarrow.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOCOATTAILLEANARROW_H)
#define _CGEOCOATTAILLEANARROW_H

#include "geographic/geopolygon.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class CGeoCoattailLeanArrow : public CGeoPolygon
	{
	public:
		void Operation1();
	};
}
#endif  //_CGEOCOATTAILLEANARROW_H
