//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeocoattaildirectarrow.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOCOATTAILDIRECTARROW_H)
#define _CGEOCOATTAILDIRECTARROW_H

#include "geographic/geopolygon.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class CGeoCoattailDirectArrow : public CGeoPolygon
	{
	public:
		void Operation1();
	};
}
#endif  //_CGEOCOATTAILDIRECTARROW_H
