//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeoellipse.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOELLIPSE_H)
#define _CGEOELLIPSE_H

#include "geographic/geopolygon.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class VR_GEOGRAPHIC_EXPORT CGeoEllipse 
		: public CGeoPolygon
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CGeoEllipse();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoEllipse(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CGeoEllipse();

		virtual void setRadiusMajor(const double& radiusMajor);

		virtual double getRadiusMajor();

		virtual void setRadiusMijor(const double& radiusMijor);

		virtual double getRadiusMijor();

		virtual void updateSceneObject();

		virtual void copyTo(Common::ISceneObject* pDestObject);
	protected:
		virtual bool transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry);
	protected:
		double mRadiusMajor;
		double mRadiusMijor;
	};
}
#endif  //_CGEOELLIPSE_H
