//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeofreeline.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOFREELINE_H)
#define _CGEOFREELINE_H

#include "geographic/geoline.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class VR_GEOGRAPHIC_EXPORT CGeoFreeLine : public CGeoLine
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CGeoFreeLine();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoFreeLine(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CGeoFreeLine();

		virtual void updateSceneObject();
	protected:
		virtual bool transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry);
	};
}
#endif  //_CGEOFREELINE_H
