//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : geographictype.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOGRAPHICTYPE_H)
#define _CGEOGRAPHICTYPE_H

#include "framework/core/igeopoint.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	static std::string GT_POINT = "GT_POINT";//点
	static std::string GT_MULTIPOINT = "GT_MULTIPOINT";//多点
	static std::string GT_POLYLINE = "GT_POLYLINE";//折线
	static std::string GT_POLYGON = "GT_POLYGON";//多边形
	static std::string GT_TRIANGLE = "GT_TRIANGLE";//三角形
	static std::string GT_SECTOR = "GT_SECTOR";//扇形
	static std::string GT_BOW = "GT_BOW";//弓形
	static std::string GT_ELLIPSE = "GT_ELLIPSE";//椭圆
	static std::string GT_RECTANGLE = "GT_RECTANGLE";//矩形
	static std::string GT_CIRCLE = "GT_CIRCLE";//圆
	static std::string GT_ARC = "GT_ARC";//圆弧
	static std::string GT_FREELINE = "GT_FREELINE";//自由线
	static std::string GT_BEZIERARROW = "GT_BEZIERARROW";//贝塞尔箭头
	static std::string GT_DIRECTARROW = "GT_DIRECTARROW";//直箭头
	static std::string GT_COATTAILDIRECTARROW = "GT_COATTAILDIRECTARROW";//燕尾直箭头
	static std::string GT_COATTAILLEANARROW = "GT_COATTAILLEANARROW";//燕尾协箭头
	static std::string GT_DOUBLEARROW = "GT_DOUBLEARROW";//双箭头
}

#endif  //_CGEOGRAPHICTYPE_H
