//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeographicconfig.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOGRAPHICCONFIG_H)
#define _CGEOGRAPHICCONFIG_H

#include <exception>
#include <stdio.h>
#include <vector>
#include <string>
#include "geographic/geographictype.h"

using namespace std;

#ifdef VR_GEOGRAPHIC_EXPORTS
# define VR_GEOGRAPHIC_EXPORT _declspec(dllexport)
#else
# define VR_GEOGRAPHIC_EXPORT _declspec(dllimport)
#endif


#endif  //_CGEOGRAPHICCONFIG_H
