//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeomultipoint.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOMULTIPOINT_H)
#define _CGEOMULTIPOINT_H

#include "framework/core/igeoline.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class CGeoMultiPoint : public Core::IGeoLine
	{
	public:
		void Operation1();
	};
}
#endif  //_CGEOMULTIPOINT_H
