//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeopoint.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOGRAPHICPOINT_H)
#define _CGEOGRAPHICPOINT_H

#include "framework/core/igeopoint.h"
#include <osgEarthSymbology/Style>
#include "geographic/geographicconfig.h"

namespace Graphic
{
	/// <summary>
	/// CGeoPoint类，继承IGeoPoint类：地理几何点类，用于提供表达与渲染空间点的接口
	/// </summary>
	class VR_GEOGRAPHIC_EXPORT CGeoPoint 
		: public Core::IGeoPoint
	{
    public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CGeoPoint();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoPoint(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CGeoPoint();

		/// <summary>
		/// 加载直场景
		/// </summary>
		virtual bool loadToScene();
		/// <summary>
		/// 渲染至场景
		/// </summary>
		virtual bool renderToScene();
		/// <summary>
		/// 从场景中反挂接
		/// </summary>
		virtual bool deRenderFromScene();
		/// <summary>
		/// 从场景中卸载
		/// </summary>
		virtual bool unLoadFromScene();

		virtual void updateSceneObject();

		osg::Node* getNode();
	protected:
		osg::Node* mpNode;
    };
}
#endif  //_CGEOGRAPHICPOINT_H
