//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeoroundedrectangle.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOROUNDEDRECTANGLE_H)
#define _CGEOROUNDEDRECTANGLE_H

#include "geographic/rectangle.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class CGeoRoundedRectangle : public CGeoRectangle
	{
	public:
		void Operation1();
	};
}
#endif  //_CGEOROUNDEDRECTANGLE_H
