//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeosector.h
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#if !defined(_CGEOSECTOR_H)
#define _CGEOSECTOR_H

#include "geographic/geocirlce.h"
#include "geographic/geographicconfig.h"

namespace Graphic
{
	class VR_GEOGRAPHIC_EXPORT CGeoSector
		: public CGeoCircle
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CGeoSector();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoSector(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CGeoSector();

	protected:
		virtual bool transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry);
	};
}
#endif  //_CGEOSECTOR_H
