//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : iserialisable.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/common/iserialisable.h"


namespace Common
{
	ISerialisable::ISerialisable()
	{
	
	}

	ISerialisable::~ISerialisable()
	{
	
	}

    int ISerialisable::insertToDb()
    {
		INTERFACE_NOT_IMPLEMENTED
    }
    
    int ISerialisable::updateToDb()
    {
		INTERFACE_NOT_IMPLEMENTED
    }
    
    int ISerialisable::deleteFromDb()
    {
		INTERFACE_NOT_IMPLEMENTED
    }
    
    int ISerialisable::queryFromDb()
    {
		INTERFACE_NOT_IMPLEMENTED
    }
    
}
