//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imygridlayer.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYGRIDLAYER_H)
#define _IMYGRIDLAYER_H

#include "mychartmaplib/imylayer.h"

namespace MyChart
{
	/// <summary>
	/// 经纬网图层基类
	/// </summary>
	class MYCHARTMAPLIB_EXPORT IMyGridLayer 
		: public IMyLayer
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyGridLayer();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">名称</param>
		IMyGridLayer(const QString& name);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyGridLayer();

		virtual void setRow(const int& row);

		virtual int getRow();

		virtual void setCol(const int& col);

		virtual int getCol();

		virtual QPixmap& getImage() ;

		/// <summary>
		/// 绘制图层接口
		/// </summary>
		/// <param name="pArgs">当前绘制参数</param>
		virtual bool draw(IMyDrawArgs* pArgs);

	private:
		int mRow;
		int mCol;
	};
}
#endif  //_IMYGRIDLAYER_H
