//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imyimagelayer.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYIMAGELAYER_H)
#define _IMYIMAGELAYER_H

#include "mychartmaplib/IMyLayer.h"

namespace MyChart
{
	/// <summary>
	/// 位图覆盖图层
	/// </summary>
	class MYCHARTMAPLIB_EXPORT IMyImageLayer
		: public IMyLayer
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyImageLayer();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">名称</param>
		IMyImageLayer(const QString& name);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyImageLayer();

		virtual void setXoffset(const double& xOffset);

		virtual double getXoffset();

		virtual void setYoffset(const double& yOffset);

		virtual double getYoffset();

		virtual void setRasterImage(const QImage& image);

		virtual QImage& getRasterImage();

		virtual QPixmap& getImage();

		/// <summary>
		/// 绘制
		/// </summary>
		/// <param name="pArgs">绘制参数（子类需要重写）</param>
		virtual bool draw(IMyDrawArgs* pArgs);

		static bool getExtendFromFile(QString& filePath,OGREnvelope& extend);

	protected:
		QImage mRasterImage;
		double mXoffset;
		double mYoffset;
	};
}
#endif  //_IMYIMAGELAYER_H
