//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imymap.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYMAP_H)
#define _IMYMAP_H

#include "mychartmaplib/imydrawable.h"
#include "mychartcommonlib/mygeoobject.h"


namespace MyChart
{
	class IMyLayer;
	/// <summary>
	/// 地图基类
	/// </summary>
	class MYCHARTMAPLIB_EXPORT IMyMap 
		: public IMyDrawable,public IMyGeoObject
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyMap();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">名称</param>
		IMyMap(const QString& name);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyMap();
		
		/// <summary>
		/// 获取图层集
		/// </summary>
		/// <returns>图层集</returns>
		virtual std::vector<IMyLayer*>& getLayers();

		virtual IMyLayer* getLayer(const QString& layerName);

		virtual IMyLayer* removeLayer(const QString& layerName);

	protected:
		std::vector<IMyLayer*> mLayers;
	};

	class MYCHARTMAPLIB_EXPORT IMyGeneralMap
		: public IMyMap
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyGeneralMap();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">对象名称</param>
		IMyGeneralMap(const QString& name);


		/// <summary>
		/// 图层初始化
		/// </summary>
		virtual void initial();
		
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyGeneralMap();

		/// <summary>
		/// 获取海图的最新绘制的结果
		/// </summary>
		/// <returns>最新绘制的结果</returns>
		virtual QPixmap& getImage();

		/// <summary>
		/// 绘制图层接口
		/// </summary>
		/// <param name="pArgs">当前绘制参数</param>
		virtual bool draw(IMyDrawArgs* pArgs);

		/// <summary>
		/// 绘制编辑图层接口
		/// </summary>
		/// <param name="pArgs">当前绘制参数</param>
		virtual bool drawEditingLayers(IMyDrawArgs* pArgs);

	protected:
		QPixmap mImage;
	};

}
#endif  //_IMYMAP_H
