//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imyproperty.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYPROPERTY_H)
#define _IMYPROPERTY_H

#include "mychartmaplib/mychartmaplib_global.h"


namespace MyChart
{
	/// <summary>
	/// 字段头信息类
	/// </summary>
	struct IMyDBFFieldHeader
	{
	public:
		/// <summary>
		/// 字段名
		/// </summary>
		QString FieldName;

		/// <summary>
		/// 字段类型
		/// </summary>
		QString FieldType;//原始类型为枚举类型

		/// <summary>
		/// 字段长度
		/// </summary>
		int FieldLength;
	};

	/// <summary>
	/// 属性类
	/// </summary>
	class MYCHARTMAPLIB_EXPORT IMyProperty 
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyProperty();

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyProperty();

		/// <summary>
		/// 根据字段名称获取字段的索引
		/// </summary>
		/// <param name="fieldName">字段名称</param>
		/// <returns>字段的索引</returns>
		int getFieldIndex(QString fieldName);

	public:

		std::vector<IMyDBFFieldHeader*> FieldHeaders;///<字段头信息集

		std::vector<QStringList*> RecordDBFValues;///<属性记录集
	};
}
#endif  //_IMYPROPERTY_H
