//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imyshaperecord.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYSHAPERECORD_H)
#define _IMYSHAPERECORD_H

#include "mychartmaplib/mychartmaplib_global.h"
#include "mychartmaplib/imygeometry.h"

namespace MyChart
{
	/// <summary>
	/// 图层要素记录类
	/// </summary>
	class MYCHARTMAPLIB_EXPORT IMyShapeRecord 
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="geometryType">要素的几何类型</param>
		IMyShapeRecord(const GeometryType& geometryType);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyShapeRecord();

		/// <summary>
		/// 获取记录的包围盒
		/// </summary>
		/// <returns>包围盒</returns>
		virtual OGREnvelope& getEnvelope();

	public :
		QString ID;///<唯一标识

        QString Annotation;///<注记字符

        QString Description;///<描述信息

		IVector3 AnnotationPosition;///注记位置

		int RecordIndex;

		IMyGeometry* Geometry;///<空间几何要素

	};

}

#endif  //_IMYSHAPERECORD_H
