//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imysymbol.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYSYMBOL_H)
#define _IMYSYMBOL_H

#include "mychartmaplib/mychartmaplib_global.h"


namespace MyChart
{
	
	class MYCHARTMAPLIB_EXPORT IMySymbol
	{
	public:
		IMySymbol();

		virtual ~IMySymbol();
	};

	class MYCHARTMAPLIB_EXPORT IMyPointSymbol
		: public IMySymbol
	{
	public:
		IMyPointSymbol();

		virtual ~IMyPointSymbol();

		virtual void setSize(const int& size);
		
		virtual int getSize();

		virtual void setColor(const QColor& color);
		
		virtual QColor getColor();

	private:
		QColor mColor;
		int mSize;
	};

	class MYCHARTMAPLIB_EXPORT IMyLineSymbol
		: public IMySymbol
	{
	public:
		IMyLineSymbol();

		virtual ~IMyLineSymbol();

		virtual void setWidth(const int& width);
		
		virtual int getWidth();

		virtual void setColor(const QColor& color);
		
		virtual QColor getColor();

	private:
		QColor mColor;
		int mWidth;
	};

	class MYCHARTMAPLIB_EXPORT IMyPolygonSymbol
		: public IMyLineSymbol
	{
	public:
		IMyPolygonSymbol();

		virtual ~IMyPolygonSymbol();

		virtual void setFill(const QColor& color);

		virtual QColor getFill();

	private:
		QColor mColor;

	};
}
#endif  //_IMYSYMBOL_H
