#ifndef MYCHARTCOMMONLIB_GLOBAL_H
#define MYCHARTCOMMONLIB_GLOBAL_H

#include <QtCore/qglobal.h>
#include <QString>

#ifdef MYCHARTCOMMONLIB_LIB
# define MYCHARTCOMMONLIB_EXPORT Q_DECL_EXPORT
#else
# define MYCHARTCOMMONLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MYCHARTCOMMONLIB_GLOBAL_H
