//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : iserialisable.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ISERIALISABLE_H)
#define _ISERIALISABLE_H

#include "framework/vr_globeframework_global.h"

// 可序列化对象，提供数据对象与数据源之间的通信接口
namespace Common
{
	/// <summary>
	/// 无效类
	/// </summary>
	class VR_PIPEFRAMEWORK_EXPORT ISerialisable
    {
    public:
		ISerialisable();

		virtual ~ISerialisable();
		virtual int insertToDb();
		virtual int updateToDb();
		virtual int deleteFromDb();
		virtual int queryFromDb();
    };
}

#endif  //_ISERIALISABLE_H
