//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维管线 系统架构设计
//  @ File Name : ispatialreference.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ISPATIALREFERENCE_H)
#define _ISPATIALREFERENCE_H


// 空间参考，提供数据对象的坐标系统信息
namespace Common
{
	/// <summary>
	/// 无效类
	/// </summary>
    class ISpatialReference
    {
    public:
        void equal();
    };
}

#endif  //_ISPATIALREFERENCE_H
