//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ibufferquery.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/tool/ibufferquery.h"

namespace Tool
{
    void IBufferQuery::perform()
    {
    
    }
    
}
