//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itoollistener.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/tool/itoollistener.h"



namespace Tool
{

	IToolListener::IToolListener()
	{
	
	}

	IToolListener::~IToolListener()
	{
	
	}

	//void IToolListener::onEvent(Common::IObject* pResult)
	//{
	//	INTERFACE_NOT_IMPLEMENTED
	//}
    
}
