//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys57properties.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS57PROPERTIES_H)
#define _IMYS57PROPERTIES_H

/// <summary>
/// S57Õº≤„ Ù–‘¿‡
/// </summary>
class IMyS57Properties {
public:
	void Operation1();
};

#endif  //_IMYS57PROPERTIES_H
