//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys57layerdata.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS57LAYERDATA_H)
#define _IMYS57LAYERDATA_H

#include "mycharts57datalib/mycharts57datalib_global.h"
#include "mychartmaplib/imylayer.h"
#include <vector>

namespace MyChart
{
	class IMyS57ShapeRecord;


	/// <summary>
	/// S57图层数据类
	/// </summary>
	class MYCHARTS57DATALIB_EXPORT IMyS57LayerData 
		: public IMyLayer
	{
	public:

		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS57LayerData();


		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">对象名称</param>
		IMyS57LayerData(const QString& name);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS57LayerData();

		/// <summary>
		/// 设置数据图层的别名
		/// </summary>
		/// <param name="aliasName">别名</param>
		virtual void setAliasName(const QString& aliasName);

		/// <summary>
		/// 获取数据图层的别名
		/// </summary>
		/// <returns>数据图层的别名</returns>
		virtual QString& getAliasName();

		/// <summary>
		/// 设置数据图层的父对象
		/// </summary>
		/// <param name="pRefOwner">父对象（内部引用）</param>
		virtual void setOwner(IMyGeoObject* pRefOwner);

		/// <summary>
		/// 获取数据图层的父对象
		/// </summary>
		/// <returns>父对象</returns>
		virtual IMyGeoObject* getOwner();

		/// <summary>
		/// 废弃接口（数据图层，无法进行绘制）
		/// </summary>
		/// <returns>无</returns>
		virtual QPixmap& getImage();

		/// <summary>
		/// 废弃接口（数据图层，无法进行绘制）
		/// </summary>
		/// <param name="pArgs">绘制参数</param>
		virtual bool draw(IMyDrawArgs* pArgs);

	protected:
		QString mAliasName;
		IMyGeoObject* mpRefMapData;
	};

}

#endif  //_IMYS57LAYERDATA_H
