//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys57mapdata.h
//  @ Date : 2017/10/20
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS57MAPDATA_H)
#define _IMYS57MAPDATA_H
#include "mycharts57datalib/mycharts57datalib_global.h"
#include "mychartmaplib/imymap.h"

namespace MyChart
{
	class IMyS57LayerData;
	/// <summary>
	/// S57海图数据类
	/// </summary>
	class MYCHARTS57DATALIB_EXPORT IMyS57MapData 
		: public IMyMap
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS57MapData();
		
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="name">对象名称</param>
		IMyS57MapData(const QString& name);

		/// <summary>
		/// 根据图层别名获取图层数据
		/// </summary>
		/// <param name="aliasLayerName">图层别名</param>
		IMyS57LayerData* getLayerDataByAliasName(const QString& aliasLayerName);

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS57MapData();

		/// <summary>
		/// 废弃接口（数据图层，无法进行绘制）
		/// </summary>
		/// <returns>无</returns>
		virtual QPixmap& getImage();

		/// <summary>
		/// 废弃接口（数据图层，无法进行绘制）
		/// </summary>
		/// <param name="pArgs">绘制参数</param>
		virtual bool draw(IMyDrawArgs* pArgs);
	};
}


#endif  //_IMYS57MAPDATA_H
