#ifndef MYCHARTEXPORTLIB_GLOBAL_H
#define MYCHARTEXPORTLIB_GLOBAL_H

#include <QtCore/qglobal.h>
#include <vector>

#ifdef MYCHARTEXPORTLIB_LIB
# define MYCHARTEXPORTLIB_EXPORT Q_DECL_EXPORT
#else
# define MYCHARTEXPORTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MYCHARTDRAWLIB_GLOBAL_H
