#ifndef VR_DATAGENERATER_GLOBAL_H
#define VR_DATAGENERATER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VR_DATAGENERATER_LIB
# define VR_DATAGENERATER_EXPORT Q_DECL_EXPORT
#else
# define VR_DATAGENERATER_EXPORT Q_DECL_IMPORT
#endif

#endif // VR_DATAGENERATER_GLOBAL_H
