//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ibufferquery.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IBUFFERQUERY_H)
#define _IBUFFERQUERY_H

#include "itool.h"

namespace Tool
{
	/// <summary>
	/// 无效类
	/// </summary>
    class IBufferQuery : public ITool
    {
    public:
        void perform();
    };
}

#endif  //_IBUFFERQUERY_H
