//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : iobjectquery.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_IOBJECTQUERY_H)
#define _IOBJECTQUERY_H


namespace Tool
{
	/// <summary>
	/// 无效类
	/// </summary>
    class IObjectQuery
    {
    public:
        void perform();
    };
}

#endif  //_IOBJECTQUERY_H
