//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itool.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_ITOOL_H)
#define _ITOOL_H

#include "framework/tool/itoollistener.h"
#include <vector>


namespace Tool
{
	class IToolListener;
	// ITool类:三维平台系统工具接口类，
	// 提供用户与三维场景交互监听机制的基础接口与回调机制
	class VR_PIPEFRAMEWORK_EXPORT ITool
    {
    public:
		ITool();

		virtual ~ITool();

		/*
			添加工具监听
			pRefListener：监听对象，监听对象的生命周期由外部管理，内部只是引用、使用
		*/
		virtual bool addToolListener(IToolListener* pRefListener);

		/*
			根据索引号获取工具监听
			index：监听对象索引号
		*/
		virtual IToolListener* getToolListener(const int& index);

		/*
			移除监听对象
			pListener：监听对象
		*/
		virtual bool removeToolListener(IToolListener* pListener);

		/*
			获取监听对象的个数
		*/
		virtual int getNumOfListeners();

		/*
			移除当前渲染对象资源 
		*/
		virtual void removeRenderResource();
	protected:
		/*
			强制执行各监听事件
			pResult:返回结果
		*/
		virtual void forceListenerEvents(Common::IObject* pResult);

	protected:
		std::vector<IToolListener*> mListeners;
    };
}

#endif  //_ITOOL_H
