//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CGeoBezierArrow.cpp
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#include "geographic/geobezierarrow.h"
#include "geographic/bezierarithmetric.h"

namespace Graphic
{

	CGeoBezierArrow::CGeoBezierArrow()
	{
		this->mType = Graphic::GT_BEZIERARROW;
		this->mMaxGeometryPointNum = 4;
	}


	CGeoBezierArrow::CGeoBezierArrow(osgEarth::MapNode* pRefMapNode)
		: CGeoPolygon(pRefMapNode)
	{
		this->mType = Graphic::GT_BEZIERARROW;
		this->mMaxGeometryPointNum = 4;
	}

	CGeoBezierArrow::~CGeoBezierArrow()
	{

	}

	void CGeoBezierArrow::updateSceneObject()
	{
		if (this->mpLod == NULL)
		{
			this->loadToScene();
			this->renderToScene();
		}
		CGeoPolygon::updateSceneObject();
	}

	bool CGeoBezierArrow::transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry)
	{
		bool r = false;
		if (this->getGeometry().size() >= 4)
		{
			CBezierArithmetic::createBezierArrow(this->getGeometry(),outRenderGeometry);
			r = true;
		}
		return r;
	}
}

