//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeodirectarrow.cpp
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#include "geographic/geodirectarrow.h"
#include "geographic/bezierarithmetric.h"

namespace Graphic
{

	CGeoDirectArrow::CGeoDirectArrow()
	{
		this->mType = Graphic::GT_DIRECTARROW;
		this->mMaxGeometryPointNum = 3;
	}


	CGeoDirectArrow::CGeoDirectArrow(osgEarth::MapNode* pRefMapNode)
		: CGeoPolygon(pRefMapNode)
	{
		this->mType = Graphic::GT_DIRECTARROW;
		this->mMaxGeometryPointNum = 3;	
	}

	CGeoDirectArrow::~CGeoDirectArrow()
	{

	}

	void CGeoDirectArrow::updateSceneObject()
	{
		if (this->mpLod == NULL)
		{
			this->loadToScene();
			this->renderToScene();
		}
		CGeoPolygon::updateSceneObject();
	}

	bool CGeoDirectArrow::transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry)
	{
		bool r = false;
		if (this->getGeometry().size() >= 3)
		{
			CBezierArithmetic::createDirectArrow(this->getGeometry(),outRenderGeometry);
			r = true;
		}
		return r;
	}
}

