//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeodoublearrow.cpp
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#include "geographic/geodoublearrow.h"
#include "geographic/bezierarithmetric.h"

namespace Graphic
{
	CGeoDoubleArrow::CGeoDoubleArrow()
	{
	
	}

	CGeoDoubleArrow::CGeoDoubleArrow(osgEarth::MapNode* pRefMapNode)
		:CGeoPolygon(pRefMapNode)
	{
	
	}

	CGeoDoubleArrow::~CGeoDoubleArrow()
	{
	
	}

	bool CGeoDoubleArrow::transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry)
	{
		bool r = false;
		if (this->getGeometry().size() >= 4)
		{
			CBezierArithmetic::createBezierArrow(this->getGeometry(),outRenderGeometry);
			r = true;
		}
		return r;
	}
}

