//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeofreeline.cpp
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#include "geographic/geofreeline.h"
#include "geographic/bezierarithmetric.h"
using namespace osgEarth::Symbology;


namespace Graphic
{
	CGeoFreeLine::CGeoFreeLine()
	{
		this->mType = Graphic::GT_FREELINE;
	}

	CGeoFreeLine::CGeoFreeLine(osgEarth::MapNode* pRefMapNode)
		:CGeoLine(pRefMapNode)
	{
		this->mType = Graphic::GT_FREELINE;
	}

	CGeoFreeLine::~CGeoFreeLine()
	{
	
	}
	
	void CGeoFreeLine::updateSceneObject()
	{
		if (this->mpLod == NULL)
		{
			this->loadToScene();
			this->renderToScene();
		}
		CGeoLine::updateSceneObject();
	}
	
	bool CGeoFreeLine::transformRenderGeometry(std::vector<osg::Vec3d>& outRenderGeometry)
	{
		bool r = false;
		if (this->getGeometry().size() >= 3)
		{
			CBezierArithmetic::bezierLine(this->getGeometry(),outRenderGeometry,40);
			r = true;
		}
		return r;
	}
}
