//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : cgeoroundedrectangle.cpp
//  @ Date : 2018/7/28
//  @ Author : sgeoffrey
//  @platform:蚂蚁空间信息平台
//


#include "geographic/georoundedrectangle.h"

namespace Graphic
{
	void CGeoRoundedRectangle::Operation1()
	{

	}
}
