//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeomodel.h
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#if !defined(_CGEOMODEL_H)
#define _CGEOMODEL_H

#include "framework/core/igeomodel.h"
#include "geoobject/geoobject_global.h"
#include <osgEarthUtil/ObjectLocator>
#include "framework/core/ispatialparameter.h"

namespace Geo
{
	class ISpatialParameter;
	/// <summary>
	/// CGeoModel类：:模型接口类，继承并实现IGeoModel相关接口,用于渲染本地各种三维模型，比如：.osg,osgb,3ds,ive等
	/// </summary>>
	class VR_GEOOBJECT_EXPORT CGeoModel
		: public Core::IGeoModel
    {
    public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CGeoModel();
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoModel(osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="modelURL">模型地址</param>
		/// <param name="pRefMapNode">关联的地图节点</param>
		CGeoModel(const std::string& modelURL, osgEarth::MapNode* pRefMapNode);
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CGeoModel();

		/// <summary>
		/// 加载直场景
		/// </summary>
		virtual bool loadToScene();
		/// <summary>
		/// 渲染至场景
		/// </summary>
		virtual bool renderToScene();
		/// <summary>
		/// 从场景中反挂接
		/// </summary>
		virtual bool deRenderFromScene();
		/// <summary>
		/// 从场景中卸载
		/// </summary>
		virtual bool unLoadFromScene();
	private:
		std::string mModelURL;
		osgEarth::Util::ObjectLocatorNode* mpNodeLocator;
    };
}

#endif  //_CGEOMODEL_H
