//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeopolygon.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igeopolygon.h"
#include <osgEarthSymbology/Geometry>

namespace Core
{
	IGeoPolygon::IGeoPolygon()
	{

	}

	IGeoPolygon::IGeoPolygon(osgEarth::MapNode* pRefMapNode)
		: Common::ISceneObject(pRefMapNode)
	{

	}

	IGeoPolygon::~IGeoPolygon()
	{

	}

	bool IGeoPolygon::contain(const osg::Vec3d& geoPoint)
	{
		//std::vector<osg::Vec3d>& graphicGeometry = 
		osgEarth::Symbology::Ring geometryRing;
		osg::Vec3d geometryWpoint(0,0,0);
		for(int  index = 0; index < this->getGeometry().size(); ++index)
		{
			osg::Vec3d geoPoint(this->getGeometry().at(index));
			geometryRing.push_back(geoPoint);
		}
		geometryRing.close();
		if(geometryRing.contains2D(geoPoint.x(),geoPoint.y()))
			return true;
		return false;
	}
}
