//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeopoint.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igeopoint.h"

namespace Core
{
	IGeoPoint::IGeoPoint()
	{
	
	}

	IGeoPoint::IGeoPoint(osgEarth::MapNode* pRefMapNode)
		: ISceneObject(pRefMapNode)
	{
	
	}

	IGeoPoint::~IGeoPoint()
	{
	
	}

	
    
}
