//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeorect.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igeorect.h"

namespace Core
{
    void IGeoRect::getPostion()
    {
    
    }
    
    void IGeoRect::setPosition()
    {
    
    }
    
    void IGeoRect::getWidth()
    {
    
    }
    
    void IGeoRect::setWidth()
    {
    
    }
    
    void IGeoRect::getHeight()
    {
    
    }
    
    void IGeoRect::setHeight()
    {
    
    }
    
}
