//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeomodel.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igeomodel.h"
#include "framework/core/ispatialparameter.h"

namespace Core
{
	IGeoModel::IGeoModel()
	{
		this->mpSpatialParameter = NULL;
	}

	IGeoModel::IGeoModel(osgEarth::MapNode* pRefMapNode)
		: ISceneObject(pRefMapNode)
	{
		this->mpSpatialParameter = NULL;
	}

	IGeoModel::~IGeoModel()
	{
		if (NULL != this->mpSpatialParameter)
		{
			delete this->mpSpatialParameter;
			this->mpSpatialParameter = NULL;
		}
	}

	Core::ISpatialParameter* IGeoModel::getOrCreateSpatialParameter()
	{
		if (NULL == this->mpSpatialParameter)
		{
			//this->mpSpatialParameter = new Core::ISpatialParameter();
		}
		return this->mpSpatialParameter;
	}
    
}
