//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igeosegment.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igeosegment.h"

namespace Core
{
	IGeoSegment::IGeoSegment()
	{
		this->mPoints.resize(2);
	}

	IGeoSegment::IGeoSegment(osgEarth::MapNode* pRefMapNode)
		: ISceneObject(pRefMapNode)
	{
		this->mPoints.resize(2);
	}

	IGeoSegment::~IGeoSegment()
	{
	
	}

	std::vector<osg::Vec3d>& IGeoSegment::getGeometry()
	{
		return this->mPoints;
	}

	osg::Vec3d& IGeoSegment::getStartPoint()
	{
		return this->mPoints[0];
	}

	osg::Vec3d& IGeoSegment::getEndPoint()
	{
		return this->mPoints[1];
	}
    
}
