//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : igrouplayer.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/igrouplayer.h"

namespace Core
{
	IGroupLayer::IGroupLayer()
	{

	}

	IGroupLayer::IGroupLayer(osgEarth::MapNode* pRefMapNode)
		: Core::ILayer(pRefMapNode)
	{

	}

	IGroupLayer::~IGroupLayer()
	{

	}
    
}
