//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ilayermanager.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/ilayermanager.h"

namespace Core
{
	static ILayerManager* s_LayerManager = NULL;

	ILayerManager::~ILayerManager()
	{
	
	}

	ILayerManager* ILayerManager::instance()
	{
		if (NULL == s_LayerManager)
			s_LayerManager = new ILayerManager();
		return s_LayerManager;
	}

	void ILayerManager::releaseInstance()
	{
		if (NULL != s_LayerManager)
		{
			delete s_LayerManager;
			s_LayerManager = NULL;
		}
	}

	ILayerManager::ILayerManager()
	{
	
	}

}
