//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : ispatialparameter.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/ispatialparameter.h"

namespace Core
{
	ISpatialParameter::ISpatialParameter()
	{
	
	}

	ISpatialParameter::~ISpatialParameter()
	{
	
	}

	osg::Vec3d& ISpatialParameter::getRotate()
	{
		return this->mRotate;
	}

	void ISpatialParameter::setRotate(const  osg::Vec3d& rotate)
	{
		this->mRotate = rotate;
	}

	osg::Vec3d& ISpatialParameter::getScale()
	{
		return this->mScale;
	}

	void ISpatialParameter::setScale(const  osg::Vec3d& scale)
	{
		this->mScale = scale;
	}

	osg::Vec3d& ISpatialParameter::getOffset()
	{
		return this->mOffset;
	}

	void ISpatialParameter::setOffset(const  osg::Vec3d& offset)
	{
		this->mOffset = offset;
	}
    
}
