//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itopologyarc.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/itopologyarc.h"

namespace Core
{
	ITopologyArc::ITopologyArc()
	{
		this->mpRefStartTopologyPoint = NULL;
		this->mpRefEndTopologyPoint = NULL;
	}

	ITopologyArc::~ITopologyArc()
	{
	
	}

	Core::ITopologyPoint* ITopologyArc::getStartPoint()
	{
		return this->mpRefStartTopologyPoint;
	}

	void ITopologyArc::setStartPoint(Core::ITopologyPoint* pStartTopologyPoint)
	{
		this->mpRefStartTopologyPoint = pStartTopologyPoint;
	}

	Core::ITopologyPoint* ITopologyArc::getEndPoint()
	{
		return this->mpRefEndTopologyPoint;
	}

	void ITopologyArc::setEndPoint(Core::ITopologyPoint* pEndTopologyPoint)
	{
		this->mpRefEndTopologyPoint = pEndTopologyPoint;
	}
    
}
