//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 蚂蚁空间信息平台
//  @ File Name : itopologypoint.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/itopologypoint.h"

namespace Core
{
    void ITopologyPoint::perform()
    {
    
    }
    
}
