//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 三维管线 系统架构设计
//  @ File Name : itopologycreator.cpp
//  @ Date : 2017/8/21
//  @ Author : 
//
//


#include "framework/core/itopologycreator.h"

namespace Core
{
    void ITopologyCreator::createTopologyAccordingLineLayer()
    {
    
    }
    
}
