//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : cbitmappattern.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CBITMAPPATTERN_H)
#define _CBITMAPPATTERN_H

#include "mychartsymbollib/symbol.h"

namespace MyChart
{
	class CColorTable;
	/// <summary>
	/// 位图模式符号
	/// </summary>
	class CBitmapPattern : public CSymbol
	{
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		CBitmapPattern();

		/// <summary>
		/// 构造函数
		/// </summary>
		/// <param name="bitmapdata">位图数据</param>
		/// <param name="colortable">颜色表</param>
		CBitmapPattern(QString& bitmapdata, CColorTable* colortable);
		
		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~CBitmapPattern();

		/// <summary>
		/// 返回当前符号是否有效
		/// </summary>
		/// <returns>是否有效</returns>
		bool isValid();

	public:
		QString PATT;
		QString PATD;
		QString PXPO;
		QString PCRF;

		QString Value2;
		int Value3;
		int Value4;

		bool _isvalid;
	};
}
#endif  //_CBITMAPPATTERN_H
