//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : cbitmapsymbol.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CBITMAPSYMBOL_H)
#define _CBITMAPSYMBOL_H

#include "mychartsymbollib/symbol.h"


namespace MyChart
{
	class CColorTable;
	class CBitmapSymbol : public CSymbol
	{
	public:
		CBitmapSymbol();

		CBitmapSymbol(QString& bitmapdata, CColorTable* colortable);

		virtual ~CBitmapSymbol();

		bool isValid();

		void Operation1();


		QString SYMB;
		QString SYMD;
		QString SXPO;
		QString SCRF;

		bool _isvalid;
	};
}

#endif  //_CBITMAPSYMBOL_H
