//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : cciexyz.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CCIEXYZ_H)
#define _CCIEXYZ_H
#include "mychartsymbollib/mychartsymbollib_global.h"


namespace MyChart
{
	class MYCHARTSYMBOLLIB_EXPORT CCIEXYZ
	{
	public:

		CCIEXYZ(double x, double y, double z);

		virtual ~CCIEXYZ();

		double z();

		void setZ(double value);

		double x();

		void setX(double value);

		double y();

		void setY(double value);

		//static bool operator ==(CCIEYxy& item1,CCIEYxy& item2);//操作符重载

		//bool operator !=(CCIEYxy item);//操作符重载

		void Operation1();

	protected:
		double mx;
		double my;
		double mz;
	};
}
#endif  //_CCIEXYZ_H
