//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : ccolorrecord.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CCOLORRECORD_H)
#define _CCOLORRECORD_H

#include "mychartsymbollib/cieyxy.h"
#include <string>
#include "QtGui/qcolor.h"
#include "mychartsymbollib/rgb.h"

namespace MyChart
{
	class MYCHARTSYMBOLLIB_EXPORT CColorRecord
	{
	public:
		CColorRecord(const QString& code, const QString& name, const CCIEYxy& cieyxy);

		virtual ~CColorRecord();

		CRgb rgb();

		QColor color();

		static CColorRecord black();

		static CColorRecord white();

		void p();

	public:
		QString Name;
		QString Code;
		CCIEYxy Yxy;
	};
}
#endif  //_CCOLORRECORD_H
