//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : clayerinfo.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CLAYERINFO_H)
#define _CLAYERINFO_H

namespace MyChart
{
	class CLayerInfo
	{
	public:
		void Operation1();
	};
}
#endif  //_CLAYERINFO_H
