//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : crgb.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CRGB_H)
#define _CRGB_H

namespace MyChart
{
	class CRgb
	{
	public:
		CRgb();

		CRgb(int R, int G, int B);

		~CRgb();

		int getRed()
        {
			return mRed;
        }

		void setRed(int value)
		{
			mRed = (value > 255) ? 255 : ((value < 0) ? 0 : value);
		}

		int getGreen()
        {
			return mGreen;
        }

		void setGreen(int value)
		{
			mGreen = (value > 255) ? 255 : ((value < 0) ? 0 : value);
		}

		int getBlue()
        {
			return mBlue;
        }

		void setBlue(int value)
		{
			mBlue = (value > 255) ? 255 : ((value < 0) ? 0 : value);
		}

	private :
		int mRed;
        int mGreen;
        int mBlue;
	};
}
#endif  //_CRGB_H
