//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : crleobject.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CRLEOBJECT_H)
#define _CRLEOBJECT_H

#include "mychartsymbollib_global.h"
#include <QString>

namespace MyChart
{
	class MYCHARTSYMBOLLIB_EXPORT CRleObject
	{
	public:
		CRleObject();

		virtual ~CRleObject();

	public:
		int ObjectId;
		static const std::string ObjectType;
		static const std::string ObjectHeader;
		static const std::string ObjectFooter;
		static const std::string RemarkLeadIn;
	};

}
#endif  //_CRLEOBJECT_H
