//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : cvectorsymbol.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CVECTORSYMBOL_H)
#define _CVECTORSYMBOL_H

#include "mychartsymbollib/symbol.h"


namespace MyChart
{
	class CColorTable;
	class MYCHARTSYMBOLLIB_EXPORT CVectorSymbol : public CSymbol
	{
	public:
		CVectorSymbol();

		CVectorSymbol(QString& vectordata, CColorTable* colortable);

		virtual ~CVectorSymbol();

		bool isValid();

		void Operation1();


		QString SYMB;
		QString SYMD;
		QString SXPO;
		QString SCRF;

		bool _isvalid;
	};
}
#endif  //_CVECTORSYMBOL_H
