//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : cvectorline.h
//  @ Date : 2017/9/27
//  @ Author : sgeoffrey
//
//


#if !defined(_CVECTORLINE_H)
#define _CVECTORLINE_H

#include "mychartsymbollib/symbol.h"
#include <string>

namespace MyChart
{
	class CColorTable;
	class MYCHARTSYMBOLLIB_EXPORT CVectorLine : public CSymbol
	{
	public:

		CVectorLine();

		CVectorLine(QString& vectordata,CColorTable* colortable);

		virtual ~CVectorLine();

		bool isValid();

		int getOffsetX();

		void Operation1();
	public:
		QString LNST;
		QString LIND;
		QString LXPO;
		QString LCRF;
		QString ColorCode;
		bool _isvalid;

	protected:
		CColorTable* mpRefColorTable;
	};
}
#endif  //_CVECTORLINE_H
