//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys52linesymbol.h
//  @ Date : 2017/11/3
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS52LINESYMBOL_H)
#define _IMYS52LINESYMBOL_H

#include "mycharts52symbollib/imys52symbol.h"

namespace MyChart
{
	/// <summary>
    /// 基础条件线状物标所需参数
    /// </summary>
    struct ParameterOfLine
    {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		ParameterOfLine()
		{}

		/// <summary>
		/// 析构函数
		/// </summary>
		~ParameterOfLine()
		{
			if (NULL != TextString)
			{
				delete TextString;
				TextString = NULL;
			}
		}

        /// <summary>
        /// 线风格
        /// </summary>
        QString LineStyle;
        /// <summary>
        /// 要显示的字符串
        /// </summary>
        ParaOfTextString* TextString;
        /// <summary>
        /// 线填充符号
        /// </summary>
        ComplexSymbol FillSymbol;
        /// <summary>
        /// 是否在每一个位置显示符号
        /// </summary>
        bool IsShowSymbolAtEveryPosition;
        /// <summary>
        /// 是否将符号显示在线附近
        /// </summary>
        bool IsPlaceSymbolCloseToLine;
        /// <summary>
        /// 符号在线上的位置（1－>起始位置,2－>中间位置,3->终止位置）
        /// </summary>
        int SymbolPositionOnLine;
        /// <summary>
        /// 是否为安全线
        /// </summary>
        bool IsSafe;
        /// <summary>
        /// 基本参数
        /// </summary>
        BaseParameter BasePara;
    };

	/// <summary>
    /// S52基础条件线状物标风格
    /// </summary>
	class IMyS52LineSymbol : public IMyS52Symbol {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS52LineSymbol();

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS52LineSymbol();

		/// <summary>
		/// 将S52线状符号转换为绘制参数
		/// </summary>
		/// <returns>绘制参数</returns>
		CParaOfDrawSymbol* toDrawSymbol();
	public:
		/// <summary>
        /// 记录中每个部分的参数
        /// </summary>
		std::vector<ParameterOfLine*> PartsPara;

		 /// <summary>
        /// 是否需要解析记录的每个部分
        /// </summary>
		bool IsNeedIntoParts;

		/// <summary>
        /// 线符号参数
        /// </summary>
		ParameterOfLine RecordPara;
	};
}
#endif  //_IMYS52LINESYMBOL_H
