//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys52layersymbol.h
//  @ Date : 2017/11/3
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS52LAYERSYMBOL_H)
#define _IMYS52LAYERSYMBOL_H

#include "mycharts52symbollib/imys52symbol.h"

namespace MyChart
{
	/// <summary>
	/// S52图层风格类
	/// </summary>
	class IMyS52LayerSymbol : public IMyS52Symbol {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS52LayerSymbol();

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS52LayerSymbol();

	public:
		std::vector<IMyS52Symbol*> RecordSymbols;///<图层中各记录的绘制风格集合

	};
}
#endif  //_IMYS52LAYERSYMBOL_H
