//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys52pointsymbol.h
//  @ Date : 2017/11/3
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS52POINTSYMBOL_H)
#define _IMYS52POINTSYMBOL_H

#include "mycharts52symbollib/imys52symbol.h"

namespace MyChart
{
	/// <summary>
	/// 点状符号参数
	/// </summary>
	struct ParameterOfPoint
    {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		ParameterOfPoint()
		{}

		/// <summary>
		/// 析构函数
		/// </summary>
		~ParameterOfPoint()
		{
			std::vector<ParaOfTextString*> TextStringList;
			for (int i = 0; i < TextStringList.size(); ++i)
			{
				delete TextStringList.at(i);
			}
			TextStringList.clear();
		}
        /// <summary>
        /// 单个点符号
        /// </summary>
        ComplexSymbol SingleSymbol;
        /// <summary>
        /// 点列表
        /// </summary>
		std::vector<ComplexSymbol> SymbolList;
        /// <summary>
        /// 位置是否精确
        /// </summary>
        bool IsAccurate;
        /// <summary>
        /// 是否显示危险物标
        /// </summary>
        bool IsShowDanger;
        /// <summary>
        /// 要显示的字符串
        /// </summary>
        QString TextString;
        /// <summary>
        /// 要显示的字符串（带各种参数）
        /// </summary>
        std::vector<ParaOfTextString*> TextStringList;
        /// <summary>
        /// 文本描述
        /// </summary>
        ParaOfTextString TextDescripition;
        /// <summary>
        /// 基本参数
        /// </summary>
        BaseParameter BasePara;
        /// <summary>
        /// 有关LIGHT扇区的参数
        /// </summary>
        ParameterOfLight ParaOfLight;
       
    };

	/// <summary>
	/// S52点符号风格
	/// </summary>
	class IMyS52PointSymbol : public IMyS52Symbol {
	public:

		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS52PointSymbol();

		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS52PointSymbol();

	public:
		/// <summary>
        /// 记录中每个部分的参数
        /// </summary>
		std::vector<ParameterOfPoint*> PartsPara;

		 /// <summary>
        /// 是否需要解析记录的每个部分
        /// </summary>
		bool IsNeedIntoParts;

		/// <summary>
		/// 点符号参数
		/// </summary>
		ParameterOfPoint RecordPara;
	};
}
#endif  //_IMYS52POINTSYMBOL_H
