//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : MyS57Chart
//  @ File Name : imys52areasymbol.h
//  @ Date : 2017/11/3
//  @ Author : sgeoffrey
//
//


#if !defined(_IMYS52AREASYMBOL_H)
#define _IMYS52AREASYMBOL_H

#include "mycharts52symbollib/imys52symbol.h"

namespace MyChart
{
	/// <summary>
	/// 面状符号参数
	/// </summary>
	struct ParameterOfArea
    {
	public :

		/// <summary>
		/// 构造函数
		/// </summary>
		ParameterOfArea()
		{
			TextStringList = NULL;
		}

		/// <summary>
		/// 析构函数
		/// </summary>
		~ParameterOfArea()
		{
			if (NULL != TextStringList)
			{
				delete TextStringList;
				TextStringList = NULL;
			}
		}
        /// <summary>
        /// 面填充颜色
        /// </summary>
        QString FillColor;
        /// <summary>
        /// 面边界线风格
        /// </summary>
        QString OutLineStyle;
        /// <summary>
        /// 面填充模式（特殊符号）
        /// </summary>
        QString FillPattern;
        /// <summary>
        /// 要显示的字符串
        /// </summary>
        ParaOfTextString* TextStringList;
        /// <summary>
        /// 单个中心符号
        /// </summary>
        ComplexSymbol SingleCenterSymbol;
        /// <summary>
        /// 面中心符号列表（特殊符号）
        /// </summary>
        std::vector<ComplexSymbol> CenterSymbolList;
        /// <summary>
        /// 面中心符号的位置
        /// </summary>
        QPoint PositionOfCenterSymbol;
        /// <summary>
        /// 位置是否精确
        /// </summary>
        bool IsAccurate;
        /// <summary>
        /// 关于位置精确与否的符号列表
        /// </summary>
        std::vector<ComplexSymbol> AccurateSymbolList;
        /// <summary>
        /// 是否显示危险物标
        /// </summary>
        bool IsShowDanger;
        /// <summary>
        /// 关于危险与否符号列表
        /// </summary>
		std::vector<ComplexSymbol> DangerSymbolList;
        /// <summary>
        /// 基本参数
        /// </summary>
        BaseParameter BasePara;
        
    };

	/// <summary>
	/// 面状风格
	/// </summary>
	class IMyS52AreaSymbol : public IMyS52Symbol {
	public:
		/// <summary>
		/// 构造函数
		/// </summary>
		IMyS52AreaSymbol();


		/// <summary>
		/// 析构函数
		/// </summary>
		virtual ~IMyS52AreaSymbol();

		/// <summary>
		/// 将面状风格转换成绘制参数
		/// </summary>
		CParaOfDrawSymbol* toDrawSymbol();
	public:

		/// <summary>
        /// 记录中每个部分的参数
        /// </summary>
		std::vector<ParameterOfArea*> PartsPara;

		 /// <summary>
        /// 是否需要解析记录的每个部分
        /// </summary>
		bool IsNeedIntoParts;

		/// <summary>
        /// 记录的符号参数
        /// </summary>
		ParameterOfArea RecordPara;
	};
}
#endif  //_IMYS52AREASYMBOL_H
